name: Build and Upload Python Wheels to PyPI

on:
  push:
    branches: [ main ]
  pull_request:
    types: [ opened, reopened, synchronize]

jobs:
  build-and-upload:
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        python-version: [3.11]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install libpcl
      run: sudo apt-get update && sudo apt-get install libpcl-dev

    - name: Install poetry
      run: pipx install poetry

    - name: Install dependencies
      run: poetry install

    - name: Build wheels
      run: poetry run python setup.py bdist_wheel

    - name: Upload wheels to PyPI
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        twine upload dist/*
